version: '3.7'

services:
  mpd:
    build: "${COMPOSE_ROOT}/services/mpd"
    ports:
      - "7700:6600"
      - "8800:8000"
    volumes:
      - "${COMPOSE_ROOT}/services/mpd/mpd.conf:/etc/mpd.conf:rw"
      - "/mnt/media/music/:/var/lib/mpd/music/:ro"
      - "${COMPOSE_ROOT}/data/mpd/:/var/lib/mpd/:rw"
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    devices:
      - "/dev/snd"
