version: '3.7'

services:
  invidious:
    image: andrewzah/invidious:0.20.1-alpine3.13
    environment:
      INVIDIOUS_CONFIG_FILE: /config/invidious.yml
    depends_on:
      - postgres
    ports:
      - "3000"
    volumes:
      - "${COMPOSE_ROOT}/services/invidious/invidious.yml:/config/invidious.yml:ro"
    restart: unless-stopped
    depends_on:
      - authelia
      - postgres
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invidious.rule=Host(`invidious.zah.rocks`)"
      - "traefik.http.routers.invidious.entrypoints=websecure"
      - "traefik.http.routers.invidious.tls.certresolver=myresolver"
      - 'traefik.http.routers.invidious.middlewares=authelia@docker'
