version: '3.7'

services:
  webdav:
    image: andrewzah/caddy-webdav:2.3.0-alpine3.13
    env_file:
      - "${COMPOSE_ROOT}/services/webdav/secret.env"
    volumes:
      - "${COMPOSE_ROOT}/data/webdav/:/data/:rw"
    ports:
      - "6969"
    restart: unless-stopped
