version: '3.7'

services:
  filerun:
    image: zaggash/docker-filerun:latest
    depends_on:
      - mysql
    environment:
      PGID: 1005
      PUID: 1005
      TZ: America/New_York
    ports:
      - "80"
    volumes:
      - "${COMPOSE_ROOT}/data/filerun/:/user-files/:rw"
    restart: unless-stopped
    depends_on:
      - authelia
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filerun.rule=Host(`files.zah.rocks`)"
      - "traefik.http.routers.filerun.entrypoints=websecure"
      - 'traefik.http.routers.filerun.middlewares=authelia@docker'
      - "traefik.http.routers.filerun.tls.certresolver=myresolver"
