version: '3.7'

services:
  huginn:
    image: huginn/huginn:a61924f90333b8305365273c1746bb9ea75ede57
    environment:
      - RAILS_ENV=production
      - PORT=3000
      - FORCE_SSL=true
      - DOMAIN=huginn.zah.rocks
      - DOMAINS=huginn.zah.rocks
      - HUGINN_DOMAIN=huginn.zah.rocks
      - HUGINN_DOMAINS=huginn.zah.rocks
      - DATABASE_USERNAME=huginn
      - DATABASE_ADAPTER=postgresql
      - DATABASE_HOST=postgres
    env_file:
      - "${COMPOSE_ROOT}/services/huginn/secret.env"
    ports:
      - "3000"
    restart: unless-stopped
