version: '3.7'

services:
  lychee:
    # 02-08-2021
    image: lycheeorg/lychee:v4.2.1
    environment:
      APP_NAME: 'Lychee'
      APP_ENV: 'production'
      PHP_TZ: 'America/New_York'
      DB_HOST: 'postgres'
      DB_CONNECTION: 'pgsql'
      DB_PORT: 5432
      DB_DATABASE: 'lychee'
      DB_USERNAME: 'lychee'
    env_file:
      - "${COMPOSE_ROOT}/services/lychee/secret.env"
    ports:
      - "80"
    volumes:
      - "${COMPOSE_ROOT}/services/lychee/conf/:/conf/:rw"
      - "${COMPOSE_ROOT}/data/lychee/uploads/:/uploads/:rw"
    restart: unless-stopped
    depends_on:
      - eas
      - postgres
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lychee.rule=Host(`photos.zah.rocks`)"
      - "traefik.http.routers.lychee.entrypoints=websecure"
      - "traefik.http.routers.lychee.tls.certresolver=myresolver"
      - 'traefik.http.routers.lychee.middlewares=eas-default'
