version: '3.7'

services:
  navidrome:
    # 02-16-2020
    image: deluan/navidrome:sha-64ceb53
    environment:
      ND_PORT: 4533
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_SCANINTERVAL: 1m
      ND_ENABLETRANSCODINGCONFIG: 'true'
      ND_AUTOIMPORTPLAYLISTS: 'false'
      ND_COVERJPEGQUALITY: 85
      ND_TRANSCODINGCACHESIZE: 500MB
    ports:
        - "4533"
    volumes:
      - "${COMPOSE_ROOT}/data/navidrome:/data"
      - "/mnt/media/music:/music"
    read_only: true
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`music.zah.rocks`)"
      - "traefik.http.routers.navidrome.entrypoints=websecure"
      - "traefik.http.routers.navidrome.tls.certresolver=myresolver"
