version: '3.7'

services:
  navidrome:
    # 02-07-2020, v0.40.0
    image: deluan/navidrome:0.40.0
    environment:
      ND_PORT: 4533
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_SCANINTERVAL: 1m
      ND_ENABLETRANSCODINGCONFIG: 'true'
      ND_AUTOIMPORTPLAYLISTS: 'false'
      ND_COVERJPEGQUALITY: 85
      ND_TRANSCODINGCACHESIZE: 500MB
    ports:
        - "4533"
    volumes:
      - "${COMPOSE_ROOT}/data/navidrome:/data"
      - "/mnt/media/music:/music"
    read_only: true
    restart: unless-stopped
