version: '3.7'

services:
  nodered:
    image: nodered/node-red:latest
    environment:
      TZ: America/New_York
    env_file:
      - "${COMPOSE_ROOT}/services/nodered/secret.env"
    volumes:
      - "${COMPOSE_ROOT}/data/nodered/:/data/"
    ports:
      - "1880:1880"
    read_only: true
    restart: unless-stopped
