version: '3.7'

services:
  thelounge:
    image: linuxserver/thelounge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - "${COMPOSE_ROOT}/data/thelounge/config/:/config/:rw"
    ports:
      - "9000"
    restart: unless-stopped
