version: '3.7'

services:
  monica:
    image: monica:2-apache
    env_file:
      - "${COMPOSE_ROOT}/services/monica/secret.env"
    environment:
      APP_DISABLE_SIGNUP: 'true'
      APP_ENV: 'production'
      APP_URL: 'https://rel.zah.rocks'
      APP_TRUSTED_PROXIES: '172.18.0.4'
      DB_HOST: 'mysql'
      DB_DATABASE: 'monica'
      DB_USERNAME: 'homestead'
    volumes:
      - "${COMPOSE_ROOT}/data/monica/:/var/www/html/storage/"
    ports:
      - "80"
    depends_on:
      - authelia
      - mysql
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monicahq.rule=Host(`rel.zah.rocks`)"
      - "traefik.http.routers.monicahq.entrypoints=websecure"
      - 'traefik.http.routers.monicahq.middlewares=authelia@docker'
      - "traefik.http.routers.monicahq.tls.certresolver=myresolver"
