version: '3.7'

services:
  piwigo:
    image: linuxserver/piwigo:version-2.10.2
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'
    ports:
      - "80"
    volumes:
      - "${COMPOSE_ROOT}/data/piwigo/config:/config:rw"
    restart: unless-stopped
