version: '3.7'

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'
    devices:
      - /dev/ttyUSB0
      - /dev/ttyUSB1
    network_mode: host
    restart: unless-stopped
    volumes:
      - "${COMPOSE_ROOT}/data/homeassistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
