version: '3.7'

services:
  miniflux:
    build: 
      context: "${COMPOSE_ROOT}/services/miniflux"
    environment:
      LISTEN_ADDR: '0.0.0.0:8080'
    env_file:
      - "${COMPOSE_ROOT}/services/miniflux/secret.env"
    ports:
      - "8080"
    restart: unless-stopped
    depends_on:
      - authelia
      - postgres
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.miniflux.rule=Host(`rss.zah.rocks`)"
      - "traefik.http.routers.miniflux.entrypoints=websecure"
      - 'traefik.http.routers.miniflux.middlewares=authelia@docker'
      - "traefik.http.routers.miniflux.tls.certresolver=myresolver"
