version: '3.7'

services:
  redis:
    image: redis:6-alpine
    command: 'redis-server /redis.conf'
    ports:
      - "6379"
    volumes:
      - "${COMPOSE_ROOT}/services/redis/redis.conf:/redis.conf"
      - "${COMPOSE_ROOT}/data/redis/data:/data"
    restart: unless-stopped
